name: Generate SBOM & Scan with Grype

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM
      run: |
        syft docker.io/jkkarthick/httpd:v1.0 -o spdx-json > spdx.json

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: spdx-report
        path: spdx.json

  scan-vulnerabilities:
    runs-on: ubuntu-latest
    needs: generate-sbom  # Ensures SBOM is generated before scanning

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Download SBOM Artifact
      uses: actions/download-artifact@v4
      with:
        name: spdx-report
        path: ./

    - name: Scan for Vulnerabilities with Grype
      run: |
        grype sbom:spdx.json -o json > grype-report.json

    - name: Extract Critical Vulnerabilities
      run: |
        jq '[.matches[] | select(.vulnerability.severity == "Critical") ]' grype-report.json > critical-vulnerabilities.json

    - name: Extract High Vulnerabilities
      run: |
        jq '[.matches[] | select(.vulnerability.severity == "High") ]' grype-report.json > high-vulnerabilities.json

    - name: Upload Grype Vulnerability Report
      uses: actions/upload-artifact@v4
      with:
        name: grype-vulnerability-report
        path: grype-report.json

    - name: Upload Critical Vulnerability Report
      uses: actions/upload-artifact@v4
      with:
        name: critical-vulnerabilities
        path: critical-vulnerabilities.json

    - name: Upload High Vulnerability Report
      uses: actions/upload-artifact@v4
      with:
        name: high-vulnerabilities
        path: high-vulnerabilities.json

    - name: Fail if Critical or High Vulnerabilities Exist
      run: |
        if [ $(jq '[.matches[] | select(.vulnerability.severity == "Critical" or .vulnerability.severity == "High") ] | length' grype-report.json) -gt 0 ]; then
          echo "Critical or High vulnerabilities found. Failing pipeline!"
          exit 1
        fi
